AWSTemplateFormatVersion: 2010-09-09
Parameters:
  QSS3BucketName:
    AllowedPattern: "^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$"
    ConstraintDescription: "Quick Start bucket name can include numbers, lowercase letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen (-)."
    Default: aws-quickstart
    Description: "S3 bucket name for the Quick Start assets. Quick Start bucket name can include numbers, lowercase letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen (-)."
    Type: String
  QSS3KeyPrefix:
    AllowedPattern: "^[0-9a-zA-Z-/]*$"
    ConstraintDescription: "Quick Start key prefix can include numbers, lowercase letters, uppercase letters, hyphens (-), and forward slash (/)."
    Default: quickstart-stratus360-connect-with-service/
    Description: "S3 key prefix for the Quick Start assets. Quick Start key prefix can include numbers, lowercase letters, uppercase letters, hyphens (-), and forward slash (/)."
    Type: String
  ContactFlowLogGroup:
    Default: ""
    Description: Amazon Connect contact flow Cloudwatch Logs group. Should be of the form "/aws/connect/{instancename}".
    Type: String
  AgentFirehoseS3KeyPrefix:
    AllowedPattern: "^[0-9a-zA-Z-/]*$"
    ConstraintDescription: Key prefix can include numbers, lowercase letters, uppercase letters, hyphens (-), and forward slash (/).
    Default: logs/agent-firehose-output/
    Description: S3 key prefix for the Agent logs. Key prefix can include numbers, lowercase letters, uppercase letters, hyphens (-), and forward slash (/).
    Type: String
  AgentFirehoseS3Compression:
    AllowedValues:
      - "UNCOMPRESSED"
      - "GZIP"
      - "ZIP"
      - "Snappy"
    ConstraintDescription: "Compression type must be one of the following: UNCOMPRESSED | GZIP | ZIP | Snappy"
    Default: GZIP
    Description: "Compression type must be one of the following: UNCOMPRESSED | GZIP | ZIP | Snappy"
    Type: String
  CtrFirehoseS3KeyPrefix:
    AllowedPattern: "^[0-9a-zA-Z-/]*$"
    ConstraintDescription: Key prefix can include numbers, lowercase letters, uppercase letters, hyphens (-), and forward slash (/).
    Default: logs/ctr-firehose-output/
    Description: S3 key prefix for the Agent logs. Key prefix can include numbers, lowercase letters, uppercase letters, hyphens (-), and forward slash (/).
    Type: String
  CtrFirehoseS3Compression:
    AllowedValues:
      - "UNCOMPRESSED"
      - "GZIP"
      - "ZIP"
      - "Snappy"
    ConstraintDescription: "Compression type must be one of the following: UNCOMPRESSED | GZIP | ZIP | Snappy"
    Default: "GZIP"
    Description: "Compression type must be one of the following: UNCOMPRESSED | GZIP | ZIP | Snappy"
    Type: String
  ContactFlowS3KeyPrefix:
    AllowedPattern: "^[0-9a-zA-Z-/]*$"
    ConstraintDescription: Key prefix can include numbers, lowercase letters, uppercase letters, hyphens (-), and forward slash (/).
    Default: logs/contactflowlogs-output/
    Description: S3 key prefix for the Agent logs. Key prefix can include numbers, lowercase letters, uppercase letters, hyphens (-), and forward slash (/).
    Type: String
  AgentKinesisStreamArn:
    Type: String
  CtrKinesisStreamArn:
    Type: String
  AmznConnectOutputBucketName:
    Type: String
  AmznConnectOutputBucketArn:
    Type: String
  CopyLambdaSourceBucket:
    Type: String
Conditions:
  ContactFlowLogGroupExists: !Not
    - !Equals
      - Ref: ContactFlowLogGroup
      - ""
Resources:
  AgentFirehose:
    Properties:
      DeliveryStreamType: KinesisStreamAsSource
      S3DestinationConfiguration:
        BucketARN:
          Ref: AmznConnectOutputBucketArn
        Prefix: !Ref AgentFirehoseS3KeyPrefix
        CompressionFormat: !Ref AgentFirehoseS3Compression
        BufferingHints:
          IntervalInSeconds: 60
          SizeInMBs: 1
        RoleARN:
          Fn::GetAtt:
            - FirehoseRole
            - Arn
      KinesisStreamSourceConfiguration:
        KinesisStreamARN:
          Ref: AgentKinesisStreamArn
        RoleARN:
          Fn::GetAtt:
            - FirehoseRole
            - Arn
    Type: AWS::KinesisFirehose::DeliveryStream
  CtrFirehose:
    Properties:
      DeliveryStreamType: KinesisStreamAsSource
      S3DestinationConfiguration:
        BucketARN:
          Ref: AmznConnectOutputBucketArn
        Prefix: !Ref CtrFirehoseS3KeyPrefix
        CompressionFormat: !Ref CtrFirehoseS3Compression
        BufferingHints:
          IntervalInSeconds: 60
          SizeInMBs: 1
        RoleARN:
          Fn::GetAtt:
            - FirehoseRole
            - Arn
      KinesisStreamSourceConfiguration:
        KinesisStreamARN:
          Ref: CtrKinesisStreamArn
        RoleARN:
          Fn::GetAtt:
            - FirehoseRole
            - Arn
    Type: AWS::KinesisFirehose::DeliveryStream
  CwLogsToS3Lambda:
    Properties:
      CodeUri:
        Bucket:
          Ref: CopyLambdaSourceBucket
        Key: !Sub ${QSS3KeyPrefix}functions/deploy-es-false-cwl-logs.zip
      Description: Contact flow Cloudwatch logs to S3
      Environment:
        Variables:
          S3_BUCKET:
            Ref: AmznConnectOutputBucketName
          S3_PREFIX: !Ref ContactFlowS3KeyPrefix
      Handler: index.handler
      MemorySize: 128
      Role:
        Fn::GetAtt:
          - CwLogsToS3LambdaRole
          - Arn
      Runtime: nodejs12.x
      Timeout: 300
    Type: AWS::Serverless::Function
  ContactFlowLogFilter:
    Condition: ContactFlowLogGroupExists
    DependsOn: CwLogsToS3LambdaInvoke
    Properties:
      DestinationArn:
        Fn::GetAtt:
          - CwLogsToS3Lambda
          - Arn
      FilterPattern: ""
      LogGroupName:
        Ref: ContactFlowLogGroup
    Type: AWS::Logs::SubscriptionFilter
  CwLogsToS3LambdaInvoke:
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - CwLogsToS3Lambda
          - Arn
      Principal:
        Fn::Join:
          - ""
          - - logs.
            - Ref: AWS::Region
            - .amazonaws.com
      SourceAccount:
        Ref: AWS::AccountId
      SourceArn:
        Fn::Join:
          - ":"
          - - arn:aws:logs
            - Ref: AWS::Region
            - Ref: AWS::AccountId
            - log-group
            - Ref: ContactFlowLogGroup
            - "*"
    Type: AWS::Lambda::Permission
  CwLogsToS3LambdaRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
        Version: 2012-10-17
      Path: /
      Policies:
        - PolicyDocument:
            Statement:
              - Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - logs:GetLogEvents
                  - logs:DescribeLogStreams
                Effect: Allow
                Resource:
                  - arn:aws:logs:*:*:*
              - Action:
                  - s3:AbortMultipartUpload
                  - s3:GetBucketLocation
                  - s3:GetObject
                  - s3:ListBucket
                  - s3:ListBucketMultipartUploads
                  - s3:PutObject
                Effect: Allow
                Resource:
                  - Ref: AmznConnectOutputBucketArn
                  - Fn::Join:
                      - /
                      - - Ref: AmznConnectOutputBucketArn
                        - "*"
            Version: 2012-10-17
          PolicyName: amznConnect-logsToS3Policy
    Type: AWS::IAM::Role
  FirehoseRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Condition:
              StringEquals:
                sts:ExternalId:
                  Ref: AWS::AccountId
            Effect: Allow
            Principal:
              Service:
                - firehose.amazonaws.com
        Version: 2012-10-17
      Path: /
      Policies:
        - PolicyDocument:
            Statement:
              - Action:
                  - s3:AbortMultipartUpload
                  - s3:GetBucketLocation
                  - s3:GetObject
                  - s3:ListBucket
                  - s3:ListBucketMultipartUploads
                  - s3:PutObject
                Effect: Allow
                Resource:
                  - Ref: AmznConnectOutputBucketArn
                  - Fn::Join:
                      - /
                      - - Ref: AmznConnectOutputBucketArn
                        - "*"
              - Action:
                  - kinesis:DescribeStream
                  - kinesis:GetShardIterator
                  - kinesis:GetRecords
                Effect: Allow
                Resource:
                  - Ref: AgentKinesisStreamArn
                  - Ref: CtrKinesisStreamArn
              - Action:
                  - kms:Decrypt
                Condition:
                  StringEquals:
                    kms:ViaService:
                      Fn::Join:
                        - .
                        - - kinesis
                          - Ref: AWS::Region
                          - amazonaws.com
                  StringLike:
                    kms:EncryptionContext:aws:kinesis:arn:
                      - Ref: AgentKinesisStreamArn
                Effect: Allow
                Resource: arn:aws:kms:region:accountid:key/%SSE_KEY_ARN%\
            Version: 2012-10-17
          PolicyName: amznConnect-firehoseRolePolicy
    Type: AWS::IAM::Role
Transform: AWS::Serverless-2016-10-31
