AWSTemplateFormatVersion: 2010-09-09
Description: 
  QuickStart logging solution for Amazon Connect. 
  Builds required resources to send logs to s3, as well as with AWS Elasticsearch service or AWS Quicksight.
  QuickStart by Tom Zhu, Stratus360, March 2020. 
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Logs/Firehose Configuration
        Parameters:
          - AmznConnectOutputBucketName
          - CtrDataStreamEnable
          - LogS3KeyPrefix
          - AgentFirehoseS3KeyPrefix
          - CtrFirehoseS3KeyPrefix
          - ContactFlowS3KeyPrefix
          - ContactFlowLogGroup
      - Label:
          default: Elasticsearch/Kibana Configuration
        Parameters:
          - ESEnable
          - ESName
          - ESInstanceType
          - ESInstanceVersion
      - Label:
          default: AWS Quick Start configuration
        Parameters:
          - QSS3BucketName
          - QSS3BucketRegion
          - QSS3KeyPrefix
    ParameterLabels:
      ContactFlowLogGroup:
        default: Amazon Connect CloudWatch Log Group
      AmznConnectOutputBucketName:
        default: S3 Deployment Bucket Name
      CtrDataStreamEnable:
        default: Enable CTR Data Stream 
      LogS3KeyPrefix:
        default: S3 prefix for All Log Data
      AgentFirehoseS3KeyPrefix:
        default: S3 prefix for Agent Log Data
      CtrFirehoseS3KeyPrefix:
        default: S3 prefix for CTR Log Data
      ContactFlowS3KeyPrefix:
        default: S3 prefix for Contact Flow Log Data
      ESEnable:
        default: Enable Elasticsearch/Kibana
      ESName:
        default: Elasticsearch Domain
      ESInstanceType:
        default: Elasticsearch Type
      ESInstanceVersion:
        default: Elasticsearch Version
      QSS3BucketName:
        default: Quick Start S3 Bucket Name
      QSS3BucketRegion:
        default: Quick Start S3 bucket region
      QSS3KeyPrefix:
        default: Quick Start S3 Key Prefix
Parameters:
  QSS3BucketName:
    AllowedPattern: "^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$"
    ConstraintDescription: "Quick Start bucket name can include numbers, lowercase letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen (-)."
    Default: aws-quickstart
    Description: "S3 bucket name for the Quick Start assets. Quick Start bucket name can include numbers, lowercase letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen (-)."
    Type: String
  QSS3KeyPrefix:
    AllowedPattern: "^[0-9a-zA-Z-/]*$"
    ConstraintDescription: "Quick Start key prefix can include numbers, lowercase letters, uppercase letters, hyphens (-), and forward slash (/)."
    Default: quickstart-stratus360-connect-with-service/
    Description: "S3 key prefix for the Quick Start assets. Quick Start key prefix can include numbers, lowercase letters, uppercase letters, hyphens (-), and forward slash (/)."
    Type: String
  ContactFlowLogGroup:
    Default: ""
    Description: Amazon Connect contact flow Cloudwatch Logs group. Usually is of the form "/aws/connect/{instancealiasname}".
    Type: String
  QSS3BucketRegion:
    Default: 'us-east-1'
    Description: "The AWS Region where the Quick Start S3 bucket (QSS3BucketName) is hosted. When using your own bucket, you must specify this value."
    Type: String
  AmznConnectOutputBucketName:
    AllowedPattern: "^[0-9a-z-]*$"
    ConstraintDescription: "Name of the bucket must be between 3 and 63 chars, must contain only lowercase letters, digits , or hypens (-)."
    Default: quickstart-stratus360-connect-with-service-bucket
    Description: Name of bucket to save logs to.
    MaxLength: 63
    MinLength: 3
    Type: String
  LogS3KeyPrefix:
    AllowedPattern: "^[0-9a-zA-Z-/]*/$"
    ConstraintDescription: Key prefix can include numbers, lowercase letters, uppercase letters, hyphens (-), and forward slash (/) and must end with a forward slash (/).
    Default: logs/
    Description: S3 key prefix for all logs. Key prefix can include numbers, lowercase letters, uppercase letters, hyphens (-), and forward slash (/) and must end with a forward slash (/).
    Type: String
  AgentFirehoseS3KeyPrefix:
    AllowedPattern: "^[0-9a-zA-Z-]*$"
    ConstraintDescription: Key prefix can include numbers, lowercase letters, uppercase letters, hyphens (-), and hyphens (-).
    Default: agent-firehose-output
    Description: S3 key prefix for the Agent logs. Non-empty key prefix can include numbers, lowercase letters, uppercase letters, and hyphens (-).
    MinLength: 1
    Type: String
  CtrFirehoseS3KeyPrefix:
    AllowedPattern: "^[0-9a-zA-Z-]*$"
    ConstraintDescription: Key prefix can include numbers, lowercase letters, uppercase letters, hyphens (-), and forward slash (/).
    Default: ctr-firehose-output
    Description: S3 key prefix for the CTR logs. Non-empty key prefix can include numbers, lowercase letters, uppercase letters, and hyphens (-).
    MinLength: 1
    Type: String
  ContactFlowS3KeyPrefix:
    AllowedPattern: "^[0-9a-zA-Z-]*$"
    ConstraintDescription: Key prefix can include numbers, lowercase letters, uppercase letters, hyphens (-), and forward slash (/).
    Default: contactflowlogs-output
    Description: S3 key prefix for the Agent logs. Non-empty key prefix can include numbers, lowercase letters, uppercase letters, and hyphens (-).
    MinLength: 1
    Type: String
  CtrDataStreamEnable:
    AllowedValues:
      - "true"
      - "false"
    Default: "false"
    Description:
      Enables CTR Kinesis Data Stream. Disabling will make it so that the CTR firehose is on DirectPut instead of from the Kinesis Data stream.
      Enable only if you need the Data Stream for the CTR logs (such as with the salesforce CTI adapter). 
    Type: String
  ESEnable:
    AllowedValues:
      - "true"
      - "false"
    Default: "false"
    Description:
      Enables Elasticsearch if set true, automatically generating the resources
      for Kibana/Elasticsearch and points firehose outputs to it.
    Type: String
  ESName:
    AllowedPattern: ^[a-z][a-z0-9-]*$
    ConstraintDescription:
      The name must start with a lowercase letter and must be between 3 and 28 characters.
      Valid characters are a-z (lowercase only), 0-9, and - (hyphen).
    Default: quickstart-ac-kibana
    Description: If Elasticsearch enabled, sets the name of the instance.
    MaxLength: 28
    MinLength: 3
    Type: String
  ESInstanceType:
    AllowedValues:
      - c5.large.elasticsearch
      - c5.xlarge.elasticsearch
      - c5.2xlarge.elasticsearch
      - c5.4xlarge.elasticsearch
      - c5.9xlarge.elasticsearch
      - c5.18xlarge.elasticsearch
      - i3.large.elasticsearch
      - i3.xlarge.elasticsearch
      - i3.2xlarge.elasticsearch
      - i3.4xlarge.elasticsearch
      - i3.8xlarge.elasticsearch
      - i3.16xlarge.elasticsearch
      - m5.large.elasticsearch
      - m5.xlarge.elasticsearch
      - m5.2xlarge.elasticsearch
      - m5.4xlarge.elasticsearch
      - m5.12xlarge.elasticsearch
      - r5.large.elasticsearch
      - r5.xlarge.elasticsearch
      - r5.2xlarge.elasticsearch
      - r5.4xlarge.elasticsearch
      - r5.12xlarge.elasticsearch
      - t2.small.elasticsearch
      - t2.medium.elasticsearch
      - c4.large.elasticsearch
      - c4.xlarge.elasticsearch
      - c4.2xlarge.elasticsearch
      - c4.4xlarge.elasticsearch
      - c4.8xlarge.elasticsearch
      - i2.xlarge.elasticsearch
      - i2.2xlarge.elasticsearch
      - m4.large.elasticsearch
      - m4.xlarge.elasticsearch
      - m4.2xlarge.elasticsearch
      - m4.4xlarge.elasticsearch
      - m4.10xlarge.elasticsearch
      - r4.large.elasticsearch
      - r4.xlarge.elasticsearch
      - r4.2xlarge.elasticsearch
      - r4.4xlarge.elasticsearch
      - r4.8xlarge.elasticsearch
      - r4.16xlarge.elasticsearch
      - m3.medium.elasticsearch
      - m3.large.elasticsearch
      - m3.xlarge.elasticsearch
      - m3.2xlarge.elasticsearch
      - r3.large.elasticsearch
      - r3.xlarge.elasticsearch
      - r3.2xlarge.elasticsearch
      - r3.4xlarge.elasticsearch
      - r3.8xlarge.elasticsearch
    Default: "r5.large.elasticsearch"
    Description: If Elasticsearch enabled, sets the type/size of instance.
    Type: String
  ESInstanceVersion:
    AllowedValues:
      - 7.1
      - 6.8
      - 6.7
      - 6.5
      - 6.4
      - 6.3
      - 6.2
      - 6.0
      - 5.6
      - 5.5
      - 5.3
      - 5.1
      - 2.3
      - 1.5
    Default: 6.2
    Description: If Elasticsearch enabled, sets the Elasticsearch version.
    Type: Number
Conditions:
  UsingDefaultBucket: !Equals [!Ref QSS3BucketName, 'aws-quickstart']
  ESEnableBool: !Equals
    - Ref: ESEnable
    - "true"
  ESDisableBool: !Not [Condition: ESEnableBool]
  CtrDataStreamEnableBool: !Equals
    - Ref: CtrDataStreamEnable
    - "true"
Outputs:
  AgentOutputLocation:
    Description: S3 agent logs location.
    Export:
      Name: !Sub ${AWS::StackName}-AgentLogsS3Uri
    Value:
      Fn::Join:
        - ""
        - - s3://
          - Ref: AmznConnectOutputBucketName
          - /
          - Ref: LogS3KeyPrefix
          - Ref: AgentFirehoseS3KeyPrefix
  CtrOutputLocation:
    Description: S3 call trace records location.
    Export:
      Name: !Sub ${AWS::StackName}-CtrLogsS3Uri
    Value:
      Fn::Join:
        - ""
        - - s3://
          - Ref: AmznConnectOutputBucketName
          - /
          - Ref: LogS3KeyPrefix
          - Ref: CtrFirehoseS3KeyPrefix
  ContactFlowLogsOutputLocation:
    Description: S3 contact flow logs location.
    Export:
      Name: !Sub ${AWS::StackName}-ContactFlowS3Uri
    Value:
      Fn::Join:
        - ""
        - - s3://
          - Ref: AmznConnectOutputBucketName
          - /
          - Ref: LogS3KeyPrefix
          - Ref: ContactFlowS3KeyPrefix
Resources:
  CopyLambdaSourceBucket:
    Type: AWS::S3::Bucket
  CopyZipsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 
        !Sub 
          - https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}submodules/lambda-copyzips/templates/copy-zips.template.yaml
          - S3Region: !If [UsingDefaultBucket, !Ref 'AWS::Region', !Ref QSS3BucketRegion]
            S3Bucket: !If [UsingDefaultBucket, !Sub '${QSS3BucketName}-${AWS::Region}', !Ref QSS3BucketName]
      Parameters:
        DestinationBucket: !Ref CopyLambdaSourceBucket
        QSS3BucketName: !Ref "QSS3BucketName"
        QSS3KeyPrefix: !Ref "QSS3KeyPrefix"
        SourceObjects:
          Fn::Join:
            - ","
            - - !If [ESEnableBool, functions/deploy-es-true-cwl-logs.zip, !Ref "AWS::NoValue"]
              - !If [ESDisableBool, functions/deploy-es-false-cwl-logs.zip, !Ref "AWS::NoValue"]
              - functions/clean-contact-flow.zip
              - functions/create-ref-table.zip
  ESSetupStack:
    Condition: ESEnableBool
    DependsOn: CopyZipsStack
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 
        !Sub 
          - https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}templates/es-true.template.yaml
          - S3Region: !If [UsingDefaultBucket, !Ref 'AWS::Region', !Ref QSS3BucketRegion]
            S3Bucket: !If [UsingDefaultBucket, !Sub '${QSS3BucketName}-${AWS::Region}', !Ref QSS3BucketName]
      Parameters:
        QSS3BucketName:
          Ref: QSS3BucketName
        QSS3KeyPrefix:
          Ref: QSS3KeyPrefix
        ContactFlowLogGroup:
          Ref: ContactFlowLogGroup
        LogS3KeyPrefix:
          Ref: LogS3KeyPrefix
        AgentFirehoseS3KeyPrefix:
          Ref: AgentFirehoseS3KeyPrefix
        CtrFirehoseS3KeyPrefix:
          Ref: CtrFirehoseS3KeyPrefix
        ContactFlowS3KeyPrefix:
          Ref: ContactFlowS3KeyPrefix
        AgentKinesisStreamArn: !GetAtt AgentKinesisStream.Arn
        CtrKinesisStreamArn: !If [CtrDataStreamEnableBool, !GetAtt CtrKinesisStream.Arn, ""]
        AmznConnectOutputBucketName:
          Ref: AmznConnectOutputBucketName
        AmznConnectOutputBucketArn: !GetAtt AmznConnectOutputBucket.Arn
        CopyLambdaSourceBucket:
          Ref: CopyLambdaSourceBucket
        ESName:
          Ref: ESName
        ESInstanceType:
          Ref: ESInstanceType
        ESInstanceVersion:
          Ref: ESInstanceVersion
  SetupStack:
    Condition: ESDisableBool
    DependsOn: CopyZipsStack
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 
        !Sub 
          - https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}templates/es-false.template.yaml
          - S3Region: !If [UsingDefaultBucket, !Ref 'AWS::Region', !Ref QSS3BucketRegion]
            S3Bucket: !If [UsingDefaultBucket, !Sub '${QSS3BucketName}-${AWS::Region}', !Ref QSS3BucketName]
      Parameters:
        QSS3BucketName:
          Ref: QSS3BucketName
        QSS3KeyPrefix:
          Ref: QSS3KeyPrefix
        ContactFlowLogGroup:
          Ref: ContactFlowLogGroup
        LogS3KeyPrefix:
          Ref: LogS3KeyPrefix
        AgentFirehoseS3KeyPrefix:
          Ref: AgentFirehoseS3KeyPrefix
        CtrFirehoseS3KeyPrefix:
          Ref: CtrFirehoseS3KeyPrefix
        ContactFlowS3KeyPrefix:
          Ref: ContactFlowS3KeyPrefix
        AgentKinesisStreamArn: !GetAtt AgentKinesisStream.Arn
        CtrKinesisStreamArn: !If [CtrDataStreamEnableBool, !GetAtt CtrKinesisStream.Arn, ""]
        AmznConnectOutputBucketName:
          Ref: AmznConnectOutputBucketName
        AmznConnectOutputBucketArn: !GetAtt AmznConnectOutputBucket.Arn
        CopyLambdaSourceBucket:
          Ref: CopyLambdaSourceBucket
  AgentKinesisStream:
    Properties:
      ShardCount: 1
    Type: AWS::Kinesis::Stream
  CtrKinesisStream:
    Condition: CtrDataStreamEnableBool
    Properties:
      ShardCount: 1
    Type: AWS::Kinesis::Stream
  AmznConnectOutputBucket:
    Properties:
      BucketName:
        Ref: AmznConnectOutputBucketName
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: "s3:ObjectCreated:*"
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: flows/input
                  - Name: suffix
                    Value: ".json"
            Function: !GetAtt CleanContactFlowLambda.Arn
    Type: AWS::S3::Bucket
  CleanContactFlowLambda:
    Type: AWS::Lambda::Function
    DependsOn: CopyZipsStack
    Properties:
      Code:
        S3Bucket: !Ref CopyLambdaSourceBucket
        S3Key: !Sub ${QSS3KeyPrefix}functions/clean-contact-flow.zip
      Description: Lambda cleans a contact flow json file when placed in an s3 bucket. It will output in the a directory 'output' one up from it's current directory.
      Environment:
        Variables:
          SSM_PARAM_PATH: /connect/quickstart/s360/cleancontactflow/config
      Handler: clean-contact-flow.lambda_handler
      MemorySize: 128
      Role: !GetAtt CleanContactFlowLambdaRole.Arn
      Runtime: python3.8
      Timeout: 300
  CleanContactFlowLambdaInvoke:
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref CleanContactFlowLambda
      Principal: s3.amazonaws.com
      SourceArn: !Sub arn:aws:s3:::${AmznConnectOutputBucketName}
    Type: AWS::Lambda::Permission
  CleanContactFlowLambdaRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
        Version: 2012-10-17
      Path: /
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
      Policies:
        - PolicyName: ReadFromBucket
          PolicyDocument:
            Statement:
              - Action:
                  - s3:GetObject
                  - s3:PutObject
                Effect: Allow
                Resource:
                  - !Sub arn:aws:s3:::${AmznConnectOutputBucketName}
                  - !Sub arn:aws:s3:::${AmznConnectOutputBucketName}/*
            Version: 2012-10-17
        - PolicyName: ReadParam
          PolicyDocument:
            Statement:
              - Action:
                  - ssm:GetParameter
                Effect: Allow
                Resource:
                  - !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/connect/quickstart/s360/cleancontactflow/config
            Version: 2012-10-17
    Type: AWS::IAM::Role
  CleanContactFlowLambdaParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "/connect/quickstart/s360/cleancontactflow/config"
      Description: "Config for clean contact flow script"
      Type: String
      Value: '{"invert":false,"prioritize_depth":false,"set_loop_behaviour":false,"set_spread_behaviour":true,"depth_difference":250,"width_difference":250,"depth_offset":25,"width_offset":25,"entry":{"x":20,"y":500}}'